### PR TITLE
Fix “certificates and minors” and “hide college/school" filters

### PR DESCRIPTION
**Pull request by duarte-daniela**

### CODE REVIEW

**Review by mlsamuelson — CHANGES_REQUESTED** [review]
Daniela, It looks like this is undoing the fix that I already made for this issue (but which was reported again).

My fix  went in here: https://github.com/ASUWebPlatforms/webspark-module-asu_degree_rfi/commit/d1ddbeb5e5df5fcf2504d335e96591c866532b5a

**Comment by mlsamuelson** [comment]
And here https://github.com/ASUWebPlatforms/webspark-module-asu_degree_rfi/commit/571adfe76d04e8ea521f839f11bcb0c8851a98bf

**Comment by duarte-daniela** [comment]
@mlsamuelson I was reviewing both issues, for hide college/school: the name for the field was incorrect, so I updated from: Field_degree_list_hide_colschl to field_degree_list_hide_colschl and the "certificates and minors" just for consistency of all other fields use the function (bool), also the component expects a boolean value even if it works with a string.

**Review by mlsamuelson — APPROVED** [review]
After our conversation on this, and re-testing with the field name not capitalized, it looks like this approach is the best solve here for consistency. :) Approved.

**Pull request merged**
