### PR TITLE
WS2-1156: Use yarn for package management.

### PR DESCRIPTION
**Pull request by georgebaev**
@duarte-daniela @mlsamuelson this adds `yarn` as a package manager.

Ref.: https://asudev.jira.com/browse/WS2-1156

### CODE REVIEW

**Review by mlsamuelson — CHANGES_REQUESTED** [review]
Has this been tested? It looks like it removes the /dist folder for the `app-rfi` component.

This is an issue I had Michele and Nico look at for the `app-rfi` component - the dist folder disappearing from the package that's published, and they said they saw it, but looks like you experienced the same thing I did when checking that out.  See https://asudev.jira.com/browse/UDS-1086

**Comment by mlsamuelson** [comment]
Michele made this PR which I'm running a build on now to see if it resolves the issue: https://github.com/ASU/asu-unity-stack/pull/651

In summary, there was a commit that added the dist/ folder to the .gitignore about a month ago, so it may not have been being published.

**Comment by mlsamuelson** [comment]
The  PR from Michele fixed the package publishing issue. In the 1.3.5 version of the package, I now see the dist folder.

@georgebaev Can you update this PR with version 1.3.5 of the app-rfi component? `yarn upgrade @asu-design-system/app-rfi@1.3.5` should work. And then I'll confirm that the dist folder is back where it should be, and then this should be good.

**Comment by georgebaev** [comment]
@mlsamuelson I updated the app-rfi component, could you please review? 

cc @duarte-daniela

**Review by mlsamuelson — APPROVED** [review]

**Pull request merged**
